### ISSUE TITLE
Stickers

### ISSUE THREAD

**Issue by Lucosenza2015** [nodeschool/usac.gt#11]
Hola! Aquí va el diseño de las stickers
![stickers-nodeschool](https://cloud.githubusercontent.com/assets/12750676/8918185/b51f2874-3473-11e5-920c-1b58698ac20d.jpg)

**Comment by Bvalenzuela** [comment]
A mi me gusta el primero (Blanco, Azul y negro) y el tercero (Amarillo y negro)

**Comment by edwinallenz** [comment]
A mi tambien me encanta el primero.

**Comment by Lucosenza2015** [comment]
Hola! Aqui van las dos propuestas a imprimir. 
![stickers-nodeschool-1](https://cloud.githubusercontent.com/assets/12750676/8934474/07ea6b68-3505-11e5-89e9-f7ba13eab2d3.jpg)

**Comment by bladimir47** [comment]
A mi me llega el primero de esos dos porque asi va ha acoorde al afiche y agararmos un estandar de la parte visual, serian nuestros colores

**Comment by Bvalenzuela** [comment]
El primero!!! :D ese esta chilero

**Comment by edwinallenz** [comment]
Yo quiero los dos, jajaja.
El primero tambien me parece demole viaje con ese.
