### ISSUE TITLE
Salon para la conferencia

### ISSUE THREAD

**Issue by bladimir47** [nodeschool/usac.gt#12]
Saludos a todos, ya tenemos salon, por cuestiones administrativas no se pudo obtener el de audiovisuales pero conseguimos un salon grande con cañonera edificio T-3 salon 315 a partir de la 11:00 y para tener un tiempo extra por si nos atrasamos es hasta las 14:00

**Comment by edwinallenz** [comment]
Buenisimo bladimir, @Lucosenza2015 podrias incluir la informacion del salon en la propuesta del afiche.

:100:
