### ISSUE TITLE
Escribir README y codigo de conducta del repo, hacer un pull request

### ISSUE THREAD

**Issue by edwinallenz** [nodeschool/usac.gt#2]
Usar como template para el repo esta URL
https://github.com/nodeschool/bogota

@viktorcoradov

**Comment by VIKTORCORADOV** [comment]
que tal!!!! estaba viendo que para poder poner una imagen en el readme, hay que poner alguna dirección algo asi http://nodeschool.io/images/imagen.algo. mi pregunta es como puedo poner la imagen del logo que se eligio ayer y ponerlo en el readme??????? ya que no se como subir imagenes a nodeschool.io
Ademas vamos a usar algun meetup, twitter y correo electrónico para ponerlo en el readme algo asi como lo tienen en bogotá??
ejemplo:

## Organiza

[Meetup BogotaJS](http://bogotajs.com)

[@BogotaJS](http://twitter.com/BogotaJS)

[hola@bogotajs.com](mailto:hola@bogotajs.com)

El codigo de conducta lo estaré realizando esta semana

**Comment by edwinallenz** [comment]
Gracias @VIKTORCORADOV por todo el apoyo, tendrias que clonar este repo, alli crea una carpeta images y empujas el codigo.

Luego para hacer referencia a la imagen desde el codigo tendrias que poner el link del raw de la imagen que agregaste. 
http://www.jefclaes.be/2012/04/add-images-to-github-readme.html
Aunque contrario a este post, no me parece mala tecnica usar la version raw.
Si tenes mas dudas me avisas.

**Comment by edwinallenz** [comment]
Con el tema de los links son los siguientes
Twitter
@guatemalajs

Meetup
@osukaa no se si vamos a utilizar el de innovation o podiste gestionar uno para guatemalajs?

Correo no, para contacto hay que poner el link de abrir un issue, asi es publico y cualquiera puede participar.
https://github.com/nodeschool/usac.gt/issues/new

**Comment by osukaa** [comment]
@edwinallenz hice un meetup pero ahorita no hay nadie http://www.meetup.com/jsguatemala/ el twitter de guatemalajs no es de nosotros y no podemos agarrarlo. Hay que usar solo el facebook y meetup.
