### ISSUE TITLE
Realizar los cambios para incluir el chapter en la pagina de nodeschool

### ISSUE THREAD

**Issue by edwinallenz** [nodeschool/usac.gt#3]
Usar esto como guia
https://github.com/nodeschool/organizers/wiki/New-Chapter-Setup

**Comment by edwinallenz** [comment]
@cruzperez para agregar el chapter tenes que hacer lo siguiente
1. Hacer un fork del repo https://github.com/nodeschool/nodeschool.github.io a tu github personal.
2. Clonar tu version del repo a tu maquina https://github.com/cruzperez/nodeschool.github.io
3. Agregar el archivo "usac.json" del chapter en la carpeta chapters del repo.
4. Commitear y empujar a tu repo de nodeschool.
5. Hacer un pull request de tu repo a la organizacion de nodeschool.
NOTA: Mencioname en el PR para poder darle un vistazo antes de hacer merge con el repo de nodeschool.
Eso es todo, cualquier duda me avisas

**Comment by cruzperez** [comment]
Que tal, tengo una pequeña duda, en dónde es que te tengo que mencionar, ¿antes o después de hacer el PR?

**Comment by edwinallenz** [comment]
@cruzperez con un comentario en el PR

**Comment by edwinallenz** [comment]
Closed by PR https://github.com/nodeschool/nodeschool.github.io/issues/380
