### ISSUE TITLE
Material de promocion

### ISSUE THREAD

**Issue by edwinallenz** [nodeschool/usac.gt#4]
- Stickers http://hexb.in/sticker.html
  https://github.com/terinjokes/StickerConstructorSpec
- Para el dia del evento
  https://f.cloud.github.com/assets/39759/1540821/e52bb4ee-4d28-11e3-87d2-2bae4e3edd1b.png
- Diseno de poster digital e impreso

**Comment by bladimir47** [comment]
Los stickers estan buenos, mas cuando digan NodeSchool Usac jajajaj

**Comment by Bvalenzuela** [comment]
Estan chileros los diseños de los stickers, asi empezamos a llenar las laptos con ellos jajaja

**Comment by edwinallenz** [comment]
Este es el diseno del primer sticker que hizo @Lucosenza2015
![logo-nodeschool](https://cloud.githubusercontent.com/assets/205552/8737150/28115b68-2bdc-11e5-926d-0924a2d9ab06.jpg)

Creen que deberiamos hacer una version por cada capitulo que se habra o uno global para guatemala?
Lo bueno es que si hacemos uno global solo necesitamos una impresion de stickers.

**Comment by bladimir47** [comment]
Para mi seria uno global para que no sintamos que somos una sola comunidad aunque seamos varios... solo de sugerencia sera que se mirara mejor un volcan en ve de las montañas solo si pudieran probar a ver como se ve

**Comment by edwinallenz** [comment]
Me gusta la idea de usar volcanes, algo asi como el lago de atitlan, 
Buena idea bladimir :100: , voy a sugerir el cambio.

**Comment by Bvalenzuela** [comment]
Mira, no se que tan conveniente es agregar el año? talvez a un lado de nodeschool pegado a la linea del borde superior derecho, que se viera como en escalera, algo asi
2
...0
.....1
.......5

Asi ira pegado a la linea, pero no se que tan conveniente sea colocar el año, o si se vera bien, solo que sin los puntos, jaja esque se corrian si no les ponia nada

**Comment by edwinallenz** [comment]
Dependera de cuantos mandemos a hacer inicialmente. Si hacemos bastantes no es bueno incluir el año. Yo sugiero de momento no incluirlo.

**Comment by bladimir47** [comment]
Cabal, asi se pueden usar para diferentes años mas que ya vamos a mediados de este.. Si cabal algo tipo el volcan que tiene el escudo de la U

**Comment by Lucosenza2015** [comment]
Hola mucha, hice estas dos propuestas, qué piensan? cuál prefieren?

![logo-3](https://cloud.githubusercontent.com/assets/12750676/8758223/cdc953d6-2c9e-11e5-83b7-e1f16c392fcf.jpg)
![logo-4](https://cloud.githubusercontent.com/assets/12750676/8758224/cdc9511a-2c9e-11e5-93e2-04eafaced00c.jpg)

**Comment by bladimir47** [comment]
A mi me llegan las dos, estan buenas pero para escojer una elijo la segunda, se ve bien Guatemalteca...

**Comment by Bvalenzuela** [comment]
Estan chileras las 2, pero me inclino mas por la primera. Habra que esperar a que opinen los demas jaja

**Comment by cruzperez** [comment]
A mí también me gusta más el primer diseño

**Comment by braestuart** [comment]
A mi me parecen bien los 2 diseños, pero siento que es más atractivo el segundo diseño además de más formal.

**Comment by VIKTORCORADOV** [comment]
i vote for the second :p

**Comment by ghost** [comment]
Me gustan los dos diseños, pero si hay que elegir me gusta mas el segundo.

**Comment by braestuart** [comment]
Me parecen bien las 2 ideas pero siento mas formal, además de atractiva la segunda.

Enviado desde Correo de Windows

De: cruzperez
Enviado el: ‎viernes‎, ‎17‎ de ‎julio‎ de ‎2015 ‎5‎:‎09‎ ‎p. m.
Para: nodeschool/usac.gt

A mí también me gusta más el primer diseño

**Comment by louicruz** [comment]
Voto por el segundo diseño, es más atractivo y representativo.

**Comment by edwinallenz** [comment]
Entonces el segundo jovenes.
