### ISSUE TITLE
Buscamos Mentores

### ISSUE THREAD

**Issue by VIKTORCORADOV** [nodeschool/usac.gt#6]
!Hola! si deseas ser mentor de algún NodeSchool, Podes comunicarte por acá en este medio.

No olvides poner:

1) Usuario en twitter
2) Dónde trabajas o a qué te dedicas
3) De cuál NodeSchool te gustaría ser mentor (ya que hay varios temas :smile:)

**Comment by edwinallenz** [comment]
Tambien es necesario el usuario de github :)

**Comment by edwinallenz** [comment]
movido a mentores
https://github.com/nodeschool/usac.gt/wiki/Mentores
