### ISSUE TITLE
Información General Sobre NodeSchool

### ISSUE THREAD

**Issue by VIKTORCORADOV** [nodeschool/usac.gt#7]
Si tenes dudas o inquietudes acerca de NodeSchool u otros temas, puedes escribirnos por este medio, o bien, en:

[![Gitter](https://badges.gitter.im/Join%20Chat.svg)](https://gitter.im/nodeschool/usac.gt?utm_source=badge&utm_medium=badge&utm_campaign=pr-badge#)

**Comment by edwinallenz** [comment]
Buenisimo Vic

**Comment by Lucosenza2015** [comment]
Hey me perdi, hay que agregar eso al afiche del evento?

**Comment by edwinallenz** [comment]
No @Lucosenza2015 esto solo es un chat donde cualquiera puede hacer preguntas.

**Comment by kenny08gt** [comment]
Hasta ahora puede seguir los ejercicios de learnyounode de la primera sesión, pero que quede trabado en el ejercicio 6 Make it modular, no entiendo como hacer que el parámetro sea un callback y que recibiría donde lo llamo?
