### ISSUE TITLE
Ya aparecemos en el mapa del ecosistema de nodeschool

### ISSUE THREAD

**Issue by edwinallenz** [nodeschool/usac.gt#8]
Solo quiero compartirles esto.
![image](https://cloud.githubusercontent.com/assets/205552/8807838/39c6dba8-2f9c-11e5-86d0-82a754ba64f3.png)

@cruzperez cuando crees que podes hacer el pull request al website de nodeschool para que aparezcamos en la pagina de capitulos?

**Comment by Bvalenzuela** [comment]
Que genial :D

**Comment by cruzperez** [comment]
Hoy estaré trabajando en ello, saludos

**Comment by edwinallenz** [comment]
Vieron que ya estamos en la pagina de nodeschool como chapter???
![image](https://cloud.githubusercontent.com/assets/205552/8923198/bb69d9ae-34aa-11e5-8adf-f13a257e50bb.png)

**Comment by bladimir47** [comment]
Si se ve bastante bien eso me llega.... Yo he querido compartir esa pagina pero primero quiero publicar el afiche jajajaja
