### ISSUE TITLE
Afiche

### ISSUE THREAD

**Issue by Lucosenza2015** [nodeschool/usac.gt#9]
Que les parece si hacemos el afiche con código binario o muy hardcore?
![afiche](https://cloud.githubusercontent.com/assets/12750676/8808615/e561ac50-2fa0-11e5-89ea-2069493cdca7.jpg)

@edwin-bluekite

**Comment by Bvalenzuela** [comment]
en mi opinion creo que si esta hardcore jaja

**Comment by edwinallenz** [comment]
que rex, jajaja.

**Comment by bladimir47** [comment]
Pues si seria muy complejo, talvez lo que se puede hacer es por medio de codigo JS se cree codigo que impima la fecha de alguna forma algo compleja pero que solo los de sistemas lo podamos entender jajajaj

**Comment by Lucosenza2015** [comment]
jajajajaa y quien puede hacer ese codigo?

**Comment by edwinallenz** [comment]
Hagamos algo friendly para todos los mortales :smile:

**Comment by bladimir47** [comment]
jajajaja esa seria la otra opcion... pero sino yo creo el codigo no se que les parece

**Comment by Lucosenza2015** [comment]
Nueva opción de afiche, me cuentan que piensan
![afiche-1](https://cloud.githubusercontent.com/assets/12750676/8917765/55b470b2-3471-11e5-8204-48566ec2ddfa.jpg)

![afiche-2](https://cloud.githubusercontent.com/assets/12750676/8917766/55b5b620-3471-11e5-907f-25c21c1ab0b3.jpg)

**Comment by bladimir47** [comment]
El segundo me parece muy bien, me gusta

**Comment by Bvalenzuela** [comment]
El segundo me parece bien, esta representativo

**Comment by VIKTORCORADOV** [comment]
segunda

**Comment by edwinallenz** [comment]
segunda iguanas

**Comment by edwinallenz** [comment]
Cuantos afiches creen que tenemos que imprimir???
@braestuart

**Comment by bladimir47** [comment]
Yo considero que unos 10 o 15 en color y papel de afiche, y luego imprimir una en hoja carta para sacarle copias y con eso sacar unas 30 o 40 copias para que con esta podamos colocarla en todos los lugares que esten mas que todo los de sistemas.. no se que les parece?

**Comment by Lucosenza2015** [comment]
Aquí va el afiche, me cuentan así se los mando en pdf y en el tamaño real para impresión.
![afiche-final](https://cloud.githubusercontent.com/assets/12750676/8934174/95ae6d7a-3503-11e5-9e7f-9de9b4bcfa24.jpg)

**Comment by edwinallenz** [comment]
solo indica que es en la USAC

**Comment by Lucosenza2015** [comment]
Listo! 
![afiche-final1](https://cloud.githubusercontent.com/assets/12750676/8934286/33b80792-3504-11e5-8370-3c2f1fc224f0.jpg)

**Comment by edwinallenz** [comment]
Listo podrias mandarme el pdf por inbox, asi lo subo al repo

**Comment by Lucosenza2015** [comment]
Hola! Cuales son las especificaciones de inscripción que hay que añadir al afiche?

**Comment by edwinallenz** [comment]
Es lo que ya le habias puesto
1. El texto de inscripcion donde esta el codigo QR
2. Tambien habias hecho otro cambio

esa version no la tengo
